version: '2'

services:
  dev:
    build:
     context: .
     dockerfile: Dockerfile.dev
    command:
      - npm
      - run
      - start
    volumes:
      - .:/work
    working_dir: /work
    ports:
      - "3000:3000"
